### ISSUE TITLE
Makefile overrides CFLAGS set by packagers

### ISSUE THREAD

**Issue by mrnuke** [mylittletony/SocketMan#13]
Distros or packagers expect to be able to control the CFLAGS variable. There are many reasons to do this, such as consistency within that distribution, enabling hardened builds, etc. It's also used to specify include paths on non-root builds, which is the case with many distros, including rpm based, deb based, and buildroot based.

Most build systems provide this functionality at configuration time, and takle care of the details. Pure makefile based systems should be careful so that the CFLAGS that is passed in is respected, and not overridden.

The socketman makefile does not respect this. Thus, it is quite difficult to package sockertman without first patching the makefile.

**Comment by simonmorley** [comment]
We actually have a revised Makefile specifically for the LEDE / OpenWRT builds. Let me check if that's been added somewhere else.

Thanks for doing for us!

**Comment by mrnuke** [comment]
Do you mean the makefile in examples/openwrt? That was not working very well when I tried it.
I have a LEDE package [here](https://github.com/mrnuke/lede-gopackh/blob/socketman-devel/cucumber-tony/socketman/Makefile), but, that sort of stuff is packager territory. LEDE just happens to use makefiles (can be a .spec or anything else). 

Whatever the packaging system is, the project's main makefile needs to cooperate, and that's what I'm trying to fix here.

**Comment by AndrewMargarit** [comment]
The reviews Makefile is here - https://github.com/cucumber-tony/cucumber-feeds/blob/master/socketman/Makefile

I'll merge update the example today.
