### ISSUE TITLE
LEDE 17.01 - data not sent back to CT

### ISSUE THREAD

**Issue by AndrewMargarit** [mylittletony/SocketMan#16]
On LEDE 17.01 curl and libcurl version 7.52.1 have a bug that prevents data to be sent back to CT.
https://github.com/curl/curl/issues/1268

The error from the logs

`* PRNG seeding failed`

**Comment by simonmorley** [comment]
Yep, looks the same :(

Quick solution - disable caching in the SocketMan config: 

```
"no-cache": 1
```

I think anyway - check docs.

**Comment by AndrewMargarit** [comment]
In 7.53.1 this is fixed.
