### ISSUE TITLE
LEDE 17.01 - doesn't install from opkg [edit: LEDE 17.01.1]

### ISSUE THREAD

**Issue by tca22** [mylittletony/SocketMan#24]
Hi,

I ran the command `curl -k https://s3-eu-west-1.amazonaws.com/cucumber-feed/installer/install | ash` but it seems it adds the wrong location/path to `/etc/opkg/customfeeds.conf`, as SocketMan cannot be installed thereafter from `http://s3-eu-west-1.amazonaws.com/cucumber-feed/beta/lede/17.01.1/mips_24kc/cucumber`.

Could you please verify, if `http://s3-eu-west-1.amazonaws.com/cucumber-feed/beta/lede/17.01.1/mips_24kc/cucumber` is the right path/location?

Thanks,
Tom

**Comment by AndrewMargarit** [comment]
Hi Tom,

You are using LEDE 17.01.1
Can you do me a favour and replace `17.01.1` with `lede-17.01`  /etc/opkg/customfeeds.conf 

I'll amend the script accordingly if that's done it.

Thanks for reporting that!

**Comment by tca22** [comment]
Hi Andrew,

no, that didn’t do it.

What I have done:

1) I amended "/etc/opkg/customfeeds.conf", the line

from (old)
"src/gz cucumber-feed http://s3-eu-west-1.amazonaws.com/cucumber-feed/beta/lede/17.01.1/mips_24kc/cucumber"

to (new)
"src/gz cucumber-feed http://s3-eu-west-1.amazonaws.com/cucumber-feed/beta/lede/lede-17.01/mips_24kc/cucumber"

2)
ran the commands:

"opkg update
opkg install socketman"
  —>
“Unknown package ‘socketman'. * opkg_install_cmd: Cannot install package socketman."

3)
ran the command:

"curl -k https://s3-eu-west-1.amazonaws.com/cucumber-feed/installer/install | ash"
  —>
"
Feed already found, not adding
Downloading http://s3-eu-west-1.amazonaws.com/cucumber-feed/beta/lede/lede-17.01/mips_24kc/cucumber/Packages.gz
Updated list of available packages in /var/opkg-lists/cucumber-feed
Downloading http://s3-eu-west-1.amazonaws.com/cucumber-feed/beta/lede/lede-17.01/mips_24kc/cucumber/Packages.sig
Signature check failed.
Remove wrong Signature file.
…
Collected errors:
 * opkg_conf_parse_file: Duplicate src declaration (cucumber-feed http://s3-eu-west-1.amazonaws.com/cucumber-feed/beta/lede/17.01.1/mips_24kc/cucumber). Skipping.
Unknown package ‘socketman'.
…
Collected errors:
 * opkg_conf_parse_file: Duplicate src declaration (cucumber-feed http://s3-eu-west-1.amazonaws.com/cucumber-feed/beta/lede/17.01.1/mips_24kc/cucumber). Skipping.
 * opkg_install_cmd: Cannot install package socketman.
"

Any thoughts?

Thanks,
Tom

**Comment by simonmorley** [comment]
Please keep support related questions over on the discussions.

discuss.cucumberwifi.io
