### ISSUE TITLE
Can we integrate these SocketMan with other BackEnd API ? 

### ISSUE THREAD

**Issue by Krunalvaghasiya** [mylittletony/SocketMan#3]
First thing--> You are awesome. these is something more interesting you have developed...

we are looking for SocketMan(these) kind of solutions in opnwrt. we have a router which have opnwrt as firmware & installed coovachilli package . Now we want that our router should do communication with our live server(our BackEnd API). we want to take network level changes like limiting users,set  user time duration , change captive portal url , allocate client bandwidth n all through our backend server or API. we have our backend api in node.js with mongodb database.  So Can these socketMan work on my requirement ?

Please also tell me these socketMan is open sources or commercial ?

**Comment by simonmorley** [comment]
This section is for issues, not questions relating to the repo. 

Please ask questions on the discussions as you have here:

https://discuss.cucumberwifi.io/t/can-we-integrate-these-socketman-with-other-backend-api/1006

The license for SM can be found in the README.
