### ISSUE TITLE
Autoinstaller url broken

### ISSUE THREAD

**Issue by maaso** [mylittletony/SocketMan#50]
I'm running LEDE on a Meraki MR24 and am trying to install socketman via the autoinstaller url found [here](https://github.com/mylittletony/SocketMan/wiki/Auto-Installer). 

When trying to curl that url, it returns an XML error:

`<Error><Code>NoSuchBucket</Code><Message>The specified bucket does not exist</Message><BucketName>cucumber-feed</BucketName><RequestId>691CF69A009201E4</RequestId><HostId>hFIBRyunowMjKZD/d9A1VcvQ4Hg97k+O9sG1RSBX7sxmJlkEIAgC3adGIpW1ZLMc8emvLWuOjSc=</HostId></Error>`

I realise that this probably has something to do with the Cucumber -> CT name change, can the url be updated to reflect the new path? Thanks!

**Comment by YourHuckleberry** [comment]
Seconded.  New bucket name?

**Comment by simonmorley** [comment]
Yeah it's been moved - the only challenge is I can't find where it's been moved to.

Trying to track it down as we speak.

For the short-term, the packages repo. is here:

https://packages.ctapp.io

**Comment by AndrewMargarit** [comment]
The URL of the installer has been updated - Have a look at the docs again.

**Comment by maaso** [comment]
Running the script now returns an error when trying to fetch socketman:

`Collected errors:
 * opkg_download: Failed to download http://packages.ctapp.io/beta/lede/master/powerpc_464fp/ct/Packages.gz, wget returned 8.`

**Comment by maaso** [comment]
Running the script seems to return an error when trying to retrieve the package list from packages.ctapp.io:

Collected errors:
 * opkg_download: Failed to download http://packages.ctapp.io/beta/lede/master/powerpc_464fp/ct/Packages.gz, wget returned 8.

**Comment by AndrewMargarit** [comment]
Ah, thanks for that.
Get the script again and rerun.
